### ISSUE TITLE
many errors "Can't generate DDL for NullType, ... Unrecognized data type"

### ISSUE THREAD

**Issue by dpordomingo** [src-d/sourced-ui#219]
I could not find any issue reporting this, so I assume it's not crytical... but it would be great if we could avoid flooding **source{d} CE** logs with tons of this very same trace when initializing **source{d} CE**

from `sourced-ui` component:

```
ERROR [root] Can't generate DDL for NullType(); did you forget to specify a type on this Column?
Traceback (most recent call last):
  File "/home/superset/superset/connectors/sqla/models.py", line 899, in fetch_metadata
    datatype = col.type.compile(dialect=db_dialect).upper()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 580, in compile
    return dialect.type_compiler.process(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 400, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 91, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 3350, in visit_null
    "type on this Column?" % type_
sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?
```

one trace exactly like the one above, right after each line starting by: `ERROR [root]`

```
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'repository_id'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'blob_hash'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'BIGINT' of column 'blob_size'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'BLOB' of column 'blob_content'

ERROR [root] Unrecognized data type in blobs.repository_id
ERROR [root] Unrecognized data type in blobs.blob_hash
ERROR [root] Unrecognized data type in blobs.blob_size
ERROR [root] Unrecognized data type in blobs.blob_content

sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'commit_hash'

ERROR [root] Unrecognized data type in commit_blobs.repository_id
ERROR [root] Unrecognized data type in commit_blobs.commit_hash
ERROR [root] Unrecognized data type in commit_blobs.blob_hash

sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'file_path'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'tree_hash'

ERROR [root] Unrecognized data type in commit_files.repository_id
ERROR [root] Unrecognized data type in commit_files.commit_hash
ERROR [root] Unrecognized data type in commit_files.file_path
ERROR [root] Unrecognized data type in commit_files.blob_hash
ERROR [root] Unrecognized data type in commit_files.tree_hash
ERROR [root] Unrecognized data type in commit_trees.repository_id
ERROR [root] Unrecognized data type in commit_trees.commit_hash
ERROR [root] Unrecognized data type in commit_trees.tree_hash

sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'commit_author_name'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'commit_author_email'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'DATETIME' of column 'commit_author_when'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'committer_name'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'committer_email'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'DATETIME' of column 'committer_when'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'commit_message'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'JSON' of column 'commit_parents'

ERROR [root] Unrecognized data type in commits.repository_id
ERROR [root] Unrecognized data type in commits.commit_hash
ERROR [root] Unrecognized data type in commits.commit_author_name
ERROR [root] Unrecognized data type in commits.commit_author_email
ERROR [root] Unrecognized data type in commits.commit_author_when
ERROR [root] Unrecognized data type in commits.committer_name
ERROR [root] Unrecognized data type in commits.committer_email
ERROR [root] Unrecognized data type in commits.committer_when
ERROR [root] Unrecognized data type in commits.commit_message
ERROR [root] Unrecognized data type in commits.tree_hash
ERROR [root] Unrecognized data type in commits.commit_parents

sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'tree_entry_mode'

ERROR [root] Unrecognized data type in files.repository_id
ERROR [root] Unrecognized data type in files.file_path
ERROR [root] Unrecognized data type in files.blob_hash
ERROR [root] Unrecognized data type in files.tree_hash
ERROR [root] Unrecognized data type in files.tree_entry_mode
ERROR [root] Unrecognized data type in files.blob_content
ERROR [root] Unrecognized data type in files.blob_size

sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'ref_name'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'BIGINT' of column 'history_index'

ERROR [root] Unrecognized data type in ref_commits.repository_id
ERROR [root] Unrecognized data type in ref_commits.commit_hash
ERROR [root] Unrecognized data type in ref_commits.ref_name
ERROR [root] Unrecognized data type in ref_commits.history_index
ERROR [root] Unrecognized data type in refs.repository_id
ERROR [root] Unrecognized data type in refs.ref_name
ERROR [root] Unrecognized data type in refs.commit_hash

sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'remote_name'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'remote_push_url'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'remote_fetch_url'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'remote_push_refspec'
sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'remote_fetch_refspec'

ERROR [root] Unrecognized data type in remotes.repository_id
ERROR [root] Unrecognized data type in remotes.remote_name
ERROR [root] Unrecognized data type in remotes.remote_push_url
ERROR [root] Unrecognized data type in remotes.remote_fetch_url
ERROR [root] Unrecognized data type in remotes.remote_push_refspec
ERROR [root] Unrecognized data type in remotes.remote_fetch_refspec
ERROR [root] Unrecognized data type in repositories.repository_id

sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'TEXT' of column 'tree_entry_name'

ERROR [root] Unrecognized data type in tree_entries.repository_id
ERROR [root] Unrecognized data type in tree_entries.tree_entry_name
ERROR [root] Unrecognized data type in tree_entries.blob_hash
ERROR [root] Unrecognized data type in tree_entries.tree_hash
ERROR [root] Unrecognized data type in tree_entries.tree_entry_mode
```

**Comment by smacker** [comment]
it should be partly fixed by new gitbase: https://github.com/src-d/gitbase/issues/824

**Comment by se7entyse7en** [comment]
In particular, from the release notes, it has been fixed in version [`v0.24.0-beta1`](https://github.com/src-d/gitbase/releases/tag/v0.24.0-beta1)

**Comment by se7entyse7en** [comment]
This seems very much related to #306. Probably fixing #306 will also close this.
